theme: jekyll-theme-minimal
title: Linus Rudbeck
description: "Linus Rudbeck Github Pages"

# Analytics
analytics:
  provider: "google-gtag"
  google:
    measurement_id : "G-1X45Z1BDVM"
    anonymize_ip: false
